name: Build CrashLoopFixer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Generate Gradle Wrapper
        run: ./gradlew wrapper

      - name: Build mod
        run: ./gradlew build

      - name: Upload mod artifact
        uses: actions/upload-artifact@v3
        with:
          name: CrashLoopFixer
          path: build/libs/*.jar
